// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type StudentList struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Sex  Sex    `json:"sex"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Studentinput struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Sex  Sex    `json:"sex"`
}

type Sex string

const (
	SexUnknoe Sex = "UNKNOE"
	SexMan    Sex = "MAN"
	SexWoman  Sex = "WOMAN"
)

var AllSex = []Sex{
	SexUnknoe,
	SexMan,
	SexWoman,
}

func (e Sex) IsValid() bool {
	switch e {
	case SexUnknoe, SexMan, SexWoman:
		return true
	}
	return false
}

func (e Sex) String() string {
	return string(e)
}

func (e *Sex) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Sex(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid sex", str)
	}
	return nil
}

func (e Sex) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
